version: '3.8'

services:
  webapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5007:80"   # Map port 8080 on host to port 80 on container
    volumes:
      - ./app:/app  # Mount the host directory to the container

# Add other services if needed